setup.py, src/curvefit/diagnostics.py, src/curvefit/pv.py, src/curvefit/utils.py
- new predictive validity for residuals
=> predictive validity for residuals

src/curvefit/diagnostics.py, src/curvefit/forecaster.py, src/curvefit/model_generators.py, src/curvefit/pv.py, src/curvefit/uncertainty.py, src/curvefit/utils.py
Cleaned up the predictive validity plotting diagnostics and introduced `theta` which controls how much you scale the residuals relative to the prediction magnitude (`theta = 0`: no scaling; `theta = 1`: full scaling).
=> Predictive Validity // Uncertainty

src/curvefit/forecaster.py, src/curvefit/model.py, src/curvefit/model_generators.py, src/curvefit/pv.py
New `curvefit.model_generators.ModelPipeline` will generate draws based on uncertainty that is obtained via predictive validity metrics. `curvefit.pv.PVModel` does predictive validity. `curvefit.forecaster.Forecaster` does forecasting of the residual mean and standard devaviation based on predictive validity.
=> Uncertainty based on predictive validity

src/curvefit/forecaster.py, src/curvefit/model.py, src/curvefit/model_generators.py, src/curvefit/pv.py, src/curvefit/utils.py
Fast initialization for the fixed and random effects by only re-running the initialization step for each group when that group has data changing (i.e. when the group is going through the predictive validity evaluation).
=> Fast initialization for fixed and random effects

src/curvefit/diagnostics.py, src/curvefit/forecaster.py, src/curvefit/model_generators.py, src/curvefit/pv.py, src/curvefit/utils.py, tests/test_pv.py
New function for `ModelPipeline` that runs predictive validity and creates draws.
=> uncertainty quantification

.gitignore, Makefile, README.md, example/get_started.py, src/curvefit/utils.py
Some other changes:
1. Add a .gitignore file
2. Add optional prefix argument to make install.
3. Provide compatibility with older version of scipy (compute mad)
=> Add get_started.py example / test

src/curvefit/diagnostics.py, src/curvefit/forecaster.py, src/curvefit/model_generators.py, src/curvefit/utils.py
- Diagnostic plots for draws that let you pick which space you want to plot in (by default is the space you did predictive validity in but can override)
- Simplified the code for residual model
- Change theta (scaling) depending on whether or not the predictive validity is happening in log space or linear space
=> Better draws diagnostic plot + residual model in log/not log space

.gitignore, Makefile, docs/extract_md.py, example/get_started.py, example/sandbox.py
The following utility does the extraction:
https://bradbell.github.io/CurveFit/extract_md/extract_md/
Here is an example usage of the extraction:
https://bradbell.github.io/CurveFit/extract_md/get_started/
After you add these changes, you should be able to build the documentation with the command:
make gh-pages
I forgot to mention that this is just a first version of docs/extract_md.py. For example, it automatically edits the file mkdocs.yml. I think it would be more flexible to edit this by hand  instead and check it in. For another example, it does not yet handle extracting indented markdown code because the indentation needs to be removed.
=> Add extraction of markdown from source code files

.gitignore, src/curvefit/legacy/utils.py, src/curvefit/utils.py, tests/test_utils.py
1) Function utils.neighbor_mean_std has been accelerated
2) Old neighbor_mean_std has been moved to .legacy.utils
=> Acceleration for neighbor_mean_std

Makefile, docs/extract_md.py, example/covariate.py, example/get_started.py, example/random_effect.py, mkdocs.yml
The random effects example can be seen at:
https://bradbell.github.io/CurveFit/extract_md/random_effect_xam/
In addition, the extract_md.py spell checing has been improved to recognize latex commands.
=> Add a random effects example

src/curvefit/pipelines/_pipeline.py, src/curvefit/pv/bias_corrector.py
added bias adjustment based on GP smoothing
=> Bias (GP smoothing)

src/curvefit/core/utils.py, src/curvefit/legacy/utils.py, src/curvefit/pipelines/_pipeline.py, src/curvefit/pipelines/ap_model.py, src/curvefit/pv/forecaster.py, src/curvefit/pv/pv.py
- Using 1.4826 * MAD instead of standard deviation for residuals using the legacy utils function
- Initialization for predictive validity to avoid failed optimization
=> Robust predictive validity

mkdocs.yml, setup.py, src/curvefit/core/parameter.py, tests/core/test_parameter.py
- added tests and documentation for parameter, parameter set and variable
=> Documentation and tests for parameter

src/curvefit/models/core_model.py, tests/models/test_core_model.py
This PR supersedes #72 . 
* Added `CoreModel` class
* Not fully tested yet, but please check the interface.
=> Refactor: Core Model class

src/curvefit/models/core_model.py, src/curvefit/solvers/solvers.py, tests/models/test_core_model.py, tests/solvers/test_solvers.py
* Added more functions and properties for `CoreModel` class
* Cleaned the tests for `CoreModel` a little bit
* Added `Solver` class and simple tests
I think the only part that's missing is `GaussianMixture`. I'll add that later.
=> Refactor solver

src/curvefit/models/base.py, src/curvefit/models/core_model.py, src/curvefit/models/gaussian_mixtures.py, src/curvefit/solvers/solvers.py, tests/models/test_gaussian_mixtures.py
* Added `GaussianMixture` model
* Added a base class for models and moved `DataInputs` class there. (This is something that just came to my mind and we have not talked about this before, so if you have any thoughts please let me know!)
(Tests are to be added!)
=> Refactor Gaussian Mixture

src/curvefit/core/parameter.py, src/curvefit/models/core_model.py, src/curvefit/solvers/solvers.py
Added `SmartInitialization` in solver class. 
(This PR may have conflicts with #77 , will rebase and merge this after that one.)
=> Refactor Smart Initialization

src/curvefit/models/core_model.py, src/curvefit/solvers/solvers.py
=> Refactor Cleaning

src/curvefit/solvers/solvers.py, tests/solvers/test_solvers.py
This is a draft version of the SolverOptions class.
=> Add solver options

src/curvefit/models/core_model.py, src/curvefit/solvers/solvers.py, tests/solvers/data_and_param_simulator.py, tests/solvers/test_solvers.py
* Added `set_options` for solvers
* Fixed a bug in `predict` fun for solvers
* Added a test for smart init
=> Refactor Bug Fix and Test and Option
